#mongodb deployment definition 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
#pod level definition with four pods running
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
#container level definition with an uptime of 36,000 seconds 
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          command: ["/bin/sh", "-ec", "sleep 36000"]
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password
---
#Mongodb internal service 
apiVersion: v1
kind: Service 
metadata: 
   name: mongodb-service
spec:
  selector: 
    app: mongodb 
  ports: 
    - protocol: TCP
      port: 27017
      targetPort: 27017